
# Data types
CHAR, INT, FLOAT, DOUBLE = 'CHAR', 'INT', 'FLOAT', 'DOUBLE'
NUM_TYPE_TOKENS = [CHAR, INT, FLOAT, DOUBLE]
CHAR_CONST, INTEGER_CONST, REAL_CONST = 'CHAR_CONST', 'INTEGER_CONST', 'REAL_CONST'
STRING = 'STRING'

# Arithmetic operators
PLUS, MINUS = 'PLUS', 'MINUS'  # can be unary or binary
ASTERISK = 'ASTERISK' # can be MUL_OP or DEREFERENCE

DIV_OP, MOD_OP = 'DIV_OP', 'MOD_OP'
INC_OP, DEC_OP = 'INC_OP', 'DEC_OP'

# Bitwise operators
AMPERSAND = 'AMPERSAND',  # can be AND_OP or REFERENCE
OR_OP, XOR_OP = 'OR_OP', 'XOR_OP'
LEFT_OP, RIGHT_OP = 'LEFT_OP', 'RIGHT_OP'

# Logical operators
LT_OP, GT_OP = 'LT_OP', 'GT_OP'
LE_OP, GE_OP = 'LE_OP', 'GE_OP'
EQ_OP, NE_OP = 'EQ_OP', 'NE_OP'
LOG_AND_OP, LOG_OR_OP, LOG_NEG = 'LOG_AND_OP', 'LOG_OR_OP', 'LOG_NEG'

# Assignments
ASSIGN, MUL_ASSIGN, DIV_ASSIGN = 'ASSIGN', 'MUL_ASSIGN', 'DIV_ASSIGN'
MOD_ASSIGN, ADD_ASSIGN, SUB_ASSIGN = 'MOD_ASSIGN', 'ADD_ASSIGN', 'SUB_ASSIGN'
LEFT_ASSIGN, RIGHT_ASSIGN = 'LEFT_ASSIGN', 'RIGHT_ASSIGN'
AND_ASSIGN, XOR_ASSIGN, OR_ASSIGN = 'AND_ASSIGN', 'XOR_ASSIGN', 'OR_ASSIGN'

# Parens 
LPAREN, RPAREN = 'LPAREN', 'RPAREN'
LBRACKET, RBRACKET = 'LBRACKET', 'RBRACKET'

# Special characters
COMMA, DOT, SEMICOLON, HASH = 'COMMA', 'DOT', 'SEMICOLON', 'HASH'
COLON, QUESTION_MARK = 'COLON', 'QUESTION_MARK'

# Control flow
IF, ELSE, FOR, WHILE, RETURN, DO = 'IF', 'ELSE', 'FOR', 'WHILE', 'RETURN', 'DO'
BREAK, CONTINUE = 'BREAK', 'CONTINUE'

# Names
ID = 'ID'

# Special end of file token
EOF = 'EOF'




